---
- name: Install mysql-server
  ansible.builtin.apt:
    name:
      - mysql-server
      - python3-mysqldb
    state: present
  become: true

- name: Enable and start mysql
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true
  become: true

- name: Delete anonymous user
  ansible.mysql.mysql_user:
    login_user: "{{ snipe_db_admin_user | default(omit, true) }}"
    login_password: "{{ snipe_db_admin_password | default(omit, true) }}"
    login_unix_socket: "{{ snipe_db_admin_socket | default(omit, true) }}"
    name: ""
    host_all: true
    state: absent
  become: true

- name: Remove test database
  ansible.mysql.mysql_db:
    login_user: "{{ snipe_db_admin_user | default(omit, true) }}"
    login_password: "{{ snipe_db_admin_password | default(omit, true) }}"
    login_unix_socket: "{{ snipe_db_admin_socket | default(omit, true) }}"
    name: test
    state: absent
  become: true

- name: Create snipeit database
  ansible.mysql.mysql_db:
    login_user: "{{ snipe_db_admin_user | default(omit, true) }}"
    login_password: "{{ snipe_db_admin_password | default(omit, true) }}"
    login_unix_socket: "{{ snipe_db_admin_socket | default(omit, true) }}"
    name: "{{ snipe_db_database }}"
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
    state: present
  become: true

- name: Create snipeit user
  ansible.mysql.mysql_user:
    login_user: "{{ snipe_db_admin_user | default(omit, true) }}"
    login_password: "{{ snipe_db_admin_password | default(omit, true) }}"
    login_unix_socket: "{{ snipe_db_admin_socket | default(omit, true) }}"
    name: "{{ snipe_db_username }}"
    plugin: caching_sha2_password
    plugin_auth_string: "{{ snipe_db_password }}"
    salt: "{{ snipe_db_password_salt }}"
    priv: "{{ snipe_db_database }}.*:ALL"
    state: present
  become: true
