---
# handlers file for snipe-it

- name: Restart NGINX
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Restart PHP FPM
  become: true
  ansible.builtin.service:
    name: "php{{ snipe_php_ver }}-fpm"
    state: restarted
